spring:
  application:
    name: hotel-management-system
  datasource:
    url: jdbc:h2:mem:hoteldb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mvc:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: hotelManagementSystemSecretKey_ForJWTToken_Authentication_2023
    expirationMs: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.itransform.hms: DEBUG
    com.itransform.hms.security: DEBUG
    com.itransform.hms.security.jwt: DEBUG 